import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateCampaignPlanPDF = (office, checklist, checkboxStates = {}) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  let yPos = 20;

  // Helper function to check if we need a new page
  const checkPageBreak = (neededSpace = 20) => {
    if (yPos + neededSpace > doc.internal.pageSize.height - 20) {
      doc.addPage();
      yPos = 20;
      return true;
    }
    return false;
  };

  // Title
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text('YOUR CAMPAIGN PLAN', margin, yPos);
  yPos += 10;

  // Office details
  doc.setFontSize(14);
  doc.text(office.title, margin, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text(`${office.state} - District ${office.district}`, margin, yPos);
  yPos += 6;

  // Filing deadline
  const filingDeadline = new Date(office.filing_deadline);
  const today = new Date();
  const daysUntil = Math.ceil((filingDeadline - today) / (1000 * 60 * 60 * 24));
  
  doc.setFont(undefined, 'bold');
  doc.text('Filing Deadline: ', margin, yPos);
  doc.setFont(undefined, 'normal');
  doc.text(
    `${filingDeadline.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} (${daysUntil} days)`,
    margin + 35,
    yPos
  );
  yPos += 6;

  doc.setFont(undefined, 'bold');
  doc.text('Estimated Budget: ', margin, yPos);
  doc.setFont(undefined, 'normal');
  doc.text(office.estimated_cost, margin + 40, yPos);
  yPos += 12;

  // Divider line
  doc.setDrawColor(200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Helper to render a section
  const renderSection = (title, items) => {
    if (!items || items.length === 0) return;

    checkPageBreak(30);

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(title, margin, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');

    items.forEach(item => {
      checkPageBreak(12);

      // Checkbox
      const checkboxSize = 3;
      doc.rect(margin, yPos - 3, checkboxSize, checkboxSize);
      
      // Check mark if checked
      if (checkboxStates[item.id]) {
        doc.setFont(undefined, 'bold');
        doc.text('✓', margin + 0.5, yPos - 0.5);
        doc.setFont(undefined, 'normal');
      }

      // Task text with priority color
      if (item.priority === 'critical') {
        doc.setTextColor(220, 38, 38); // Red
      } else if (item.priority === 'high') {
        doc.setTextColor(234, 88, 12); // Orange
      } else {
        doc.setTextColor(0, 0, 0); // Black
      }

      // Wrap text if too long
      const maxWidth = pageWidth - margin - margin - 10;
      const textLines = doc.splitTextToSize(item.task, maxWidth);
      
      textLines.forEach((line, index) => {
        if (index > 0) {
          checkPageBreak(6);
        }
        doc.text(line, margin + 6, yPos);
        if (index < textLines.length - 1) {
          yPos += 5;
        }
      });

      doc.setTextColor(0, 0, 0); // Reset color
      yPos += 7;
    });

    yPos += 5;
  };

  // Render all sections
  const sections = [
    { key: 'preFilingEssentials', title: 'PRE-FILING ESSENTIALS (Do This First)' },
    { key: 'filing', title: 'FILING REQUIREMENTS' },
    { key: 'first30Days', title: 'FIRST 30 DAYS' },
    { key: 'fundraising', title: 'FUNDRAISING CHECKLIST' },
    { key: 'team', title: 'TEAM TO BUILD' },
    { key: 'fieldWork', title: 'FIELD WORK & OUTREACH' },
    { key: 'messaging', title: 'MESSAGING & COMMUNICATIONS' },
  ];

  sections.forEach(section => {
    if (checklist[section.key]) {
      renderSection(section.title, checklist[section.key]);
    }
  });

// Budget breakdown
if (checklist.budget) {
    checkPageBreak(40);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('BUDGET BREAKDOWN', margin, yPos);
    yPos += 10;
  
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
  
    Object.entries(checklist.budget).forEach(([category, percentage]) => {
      checkPageBreak(8);
      doc.setFont(undefined, 'bold');
      doc.text(category + ':', margin, yPos);
      doc.setFont(undefined, 'normal');
      doc.text(percentage, margin + 80, yPos);
      yPos += 6;
    });
  
    yPos += 10;
  }

  // Footer
  checkPageBreak(20);
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text('Generated by Decide to Run - https://www.decidetorun.com', margin, yPos);
  yPos += 5;
  doc.text(`Data sourced from FEC - Verified ${new Date().toLocaleDateString()}`, margin, yPos);

  // Save the PDF
  const filename = `campaign-plan-${office.state}-${office.district}.pdf`;
  doc.save(filename);
}